<a href="https://colab.research.google.com/github/stacykeago/Big-Data/blob/main/customerevents.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

# Upload data

In [4]:
customer= pd.read_csv('customer_events_lab.csv')
customer.head(10)

,event_time,customer_id,country,channel,device,category,action,price,quantity,discount,payment_status,delivery_minutes,rating,returned,revenue
0,2026-04-01 00:10:00,C00333,Ireland,physical_store,pos_terminal,home,purchase,48.83,2,10,paid,62.0,NaN,False,87.66
1,2026-04-01 00:15:00,C00207,Germany,web,android,beauty,review,41.95,0,0,not_applicable,NaN,4.0,False,0.00
2,2026-04-01 00:22:00,C00654,Germany,physical_store,pos_terminal,fashion,add_to_cart,30.89,0,0,not_applicable,NaN,NaN,False,0.00
3,2026-04-01 00:55:00,C00659,Ireland,physical_store,pos_terminal,grocery,return,11.86,1,0,not_applicable,NaN,NaN,True,11.86
4,2026-04-01 01:01:00,C00854,Sweden,web,android,grocery,purchase,15.87,1,10,paid,44.0,NaN,False,5.87
5,2026-04-01 01:11:00,C00550,Germany,physical_store,pos_terminal,electronics,view,97.20,0,0,not_applicable,NaN,NaN,False,0.00
6,2026-04-01 01:13:00,C00172,Sweden,web,android,sports,purchase,149.44,2,0,paid,29.0,NaN,False,298.88
7,2026-04-01 01:25:00,C00893,Germany,mobile_app,ios,fashion,view,77.51,0,0,not_applicable,NaN,NaN,False,0.00
8,2026-04-01 01:46:00,C00130,Germany,mobile_app,desktop,beauty,view,15.06,0,0,not_applicable,NaN,NaN,False,0.00
9,2026-04-01 01:47:00,C00313,United Kingdom,physical_store,pos_terminal,books,add_to_cart,12.61,0,0,not_applicable,NaN,NaN,False,0.00

In [9]:
customer.columns

Index(['event_time', 'customer_id', 'country', 'channel', 'device', 'category',
       'action', 'price', 'quantity', 'discount', 'payment_status',
       'delivery_minutes', 'rating', 'returned', 'revenue'],
      dtype='object')

# cloumns and rows

In [5]:
customer.shape

(5000, 15)

# Number of counries

In [6]:
customer['country'].unique()

array(['Ireland', 'Germany', 'Sweden', 'United Kingdom', 'Netherlands',
       'France', nan], dtype=object)

# Channels

In [7]:
customer['channel'].unique()

array(['physical_store', 'web', 'mobile_app', 'partner_marketplace'],
      dtype=object)

# category

In [10]:
customer['category'].unique()

array(['home', 'beauty', 'fashion', 'grocery', 'electronics', 'sports',
       'books'], dtype=object)

# customer actions

In [11]:
customer['action'].unique()

array(['purchase', 'review', 'add_to_cart', 'return', 'view'],
      dtype=object)

Task 2: Data quality check

## Missing countries

In [12]:
customer['country'].isnull().sum()

np.int64(75)

## missing devices

In [13]:
customer.isnull().sum()

event_time             0
customer_id            0
country               75
channel                0
device               100
category               0
action                 0
price                  0
quantity               0
discount               0
payment_status         0
delivery_minutes    3353
rating              4488
returned               0
revenue                0
dtype: int64

## Missing values are normal

## channel with Highest total revenew